apiVersion: v2
appVersion: "10.7.4"
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 10.0.14
deprecated: false
description: Fast, reliable, scalable, and easy to use open-source relational database system.
home: https://github.com/truecharts/apps/tree/master/charts/dependency/mariadb
icon: https://truecharts.org/_static/img/appicons/mariadb.png
keywords:
  - mariadb
  - mysql
  - database
  - sql
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: mariadb
sources:
  - https://github.com/bitnami/bitnami-docker-mariadb
  - https://github.com/prometheus/mysqld_exporter
  - https://mariadb.org
type: application
version: 3.0.12
annotations:
  truecharts.org/catagories: |
    - database
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
