image:
  repository: tccr.io/truecharts/nzbget
  pullPolicy: IfNotPresent
  tag: v21.1@sha256:c0720d1feaac7bbe3418971c5ea0414a37478b5da1b9a8318e28fbf150089716

service:
  main:
    ports:
      main:
        port: 10057
        targetPort: 6789

probes:
  liveness:
    enabled: false

  readiness:
    enabled: false

  startup:
    enabled: false

persistence:
  config:
    enabled: true
    mountPath: "/config"
