apiVersion: v2
appVersion: "1.11.1"
kubeVersion: '>=1.16.0-0'
version: 8.0.7
name: babybuddy
description: Helps caregivers track sleep, feedings, diaper changes, tummy time and more to learn about and predict baby's needs without (as much) guess work.
type: application
home: https://github.com/truecharts/apps/tree/master/charts/stable/babybuddy
icon: https://truecharts.org/_static/img/appicons/babybuddy.png
keywords:
  - baby
  - buddy
  - tracker
  - parents
  - parenting
sources:
  - https://github.com/babybuddy/babybuddy
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 10.0.10
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.truecharts.org/
  version: 8.0.7
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
