image:
  repository: tccr.io/truecharts/babybuddy
  pullPolicy: IfNotPresent
  tag: v1.11.1@sha256:2301f3c8701522cf73cbdd0aca54eeb39e457943e560092af9b4279a9d614587

env:
  DB_ENGINE: "django.db.backends.postgresql"
  DB_NAME: "{{ .Values.postgresql.postgresqlDatabase }}"
  DB_USER: "{{ .Values.postgresql.postgresqlUsername }}"
  DB_PORT: "5432"
  CSRF_TRUSTED_ORIGINS: ""
  DB_PASSWORD:
    secretKeyRef:
      name: dbcreds
      key: postgresql-password
  DB_HOST:
    secretKeyRef:
      name: dbcreds
      key: plainhost

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 10069
        targetPort: 8000

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

postgresql:
  enabled: true
  existingSecret: "dbcreds"
  postgresqlUsername: babybuddy
  postgresqlDatabase: babybuddy
