apiVersion: v2
appVersion: "2022.6.2"
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 10.0.10
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.truecharts.org/
  version: 8.0.7
- condition: redis.enabled
  name: redis
  repository: https://charts.truecharts.org
  version: 3.0.7
description: authentik is an open-source Identity Provider focused on flexibility and versatility.
home: https://github.com/truecharts/apps/tree/master/charts/incubator/authentik
icon: https://truecharts.org/_static/img/appicons/authentik.png
keywords:
- authentik
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: authentik
sources:
- https://github.com/goauthentik/authentik
- https://goauthentik.io/docs/
version: 2.0.6
annotations:
  truecharts.org/catagories: |
    - authentication
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
