image:
  repository: tccr.io/truecharts/lazylibrarian
  pullPolicy: IfNotPresent
  tag: latest@sha256:4683426a4d329f4d201a0532d03359b0b61e03a2ac768fcac6e12cdc436ac707

securityContext:
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 5299
        targetPort: 5299

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true
