image:
  repository: tccr.io/truecharts/dashdot
  tag: v3.6.0@sha256:dbf1db33304cd2c99a029d70ba02e2fb076a48f02ff7d71672703bfaa82e5ecf
  pullPolicy: IfNotPresent

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false
  privileged: true
  allowPrivilegeEscalation: true
  capabilities:
    add:
      - SYS_ADMIN
      - SYS_RAWIO

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

env:
  DASHDOT_PORT: "{{ .Values.service.main.ports.main.port}}"

service:
  main:
    ports:
      main:
        port: 10044

persistence:
  os:
    enabled: true
    type: hostPath
    hostPath: "/etc/os-release"
    mountPath: "/etc/os-release"
    readOnly: true
  net:
    enabled: true
    type: hostPath
    hostPath: "/proc/1/ns/net"
    mountPath: "/mnt/proc/1/ns/net"
    readOnly: true
  mem:
    enabled: true
    type: hostPath
    hostPath: "/dev/mem"
    mountPath: "/dev/mem"
    readOnly: true
