apiVersion: v2
appVersion: "0.20.1197"
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 10.0.10
deprecated: false
description: Advanced tool to create your own TrueCharts-based App
home: https://github.com/truecharts/apps/tree/master/charts/stable/custom-app
icon: https://truecharts.org/_static/img/appicons/custom-app.png
keywords:
- custom
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: custom-app
sources:
- https://github.com/truecharts/apps/tree/master/charts/stable/custom-app
type: application
version: 5.0.12
annotations:
  truecharts.org/catagories: |
    - custom
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
