image:
  repository: tccr.io/truecharts/theme-park
  pullPolicy: IfNotPresent
  tag: v1.9.5@sha256:476f347130794a5cc16ebafc6ab0c9c36496471da974fe6ada8cd2cc29614b9e

service:
  main:
    ports:
      main:
        port: 10244
        targetPort: 8080

probes:
  liveness:
    path: "/"
  readiness:
    path: "/"
  startup:
    path: "/"

persistence:
  config:
    enabled: true
    mountPath: "/config"
