apiVersion: v2
appVersion: "1.27.0.589"
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 10.0.10
deprecated: false
description: Plex Media Server
home: https://github.com/truecharts/apps/tree/master/charts/stable/plex
icon: https://truecharts.org/_static/img/appicons/plex.png
keywords:
- plex
- plex-media-server
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: plex
sources:
- https://github.com/k8s-at-home/container-images/pkgs/container/plex
type: application
version: 10.0.7
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
