image:
  repository: tccr.io/truecharts/plex
  pullPolicy: IfNotPresent
  tag: v1.27.0.5897@sha256:da3028c09d8d35bd7a223899f0a20b5ad9ac389d953ea43dd959da8745951871

service:
  main:
    ports:
      main:
        port: 32400
        targetPort: 32400

persistence:
  config:
    enabled: true
    mountPath: "/config"

env:
  ALLOWED_NETWORKS: "172.16.0.0/12,10.0.0.0/8,192.168.0.0/16"
  ADVERTISE_IP: ""
  PLEX_CLAIM: ""
