image:
  repository: tccr.io/truecharts/leaf2mqtt
  tag: v0.6@sha256:7d5f45372440daf9e26ca1fafad13b2c00e7b033423c2b0a57581e95e6af784c
  pullPolicy: IfNotPresent

service:
  main:
    enabled: false
    ports:
      main:
        enabled: false

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false

secretEnv:
  LEAF_USERNAME: "leafuser"
  LEAF_PASSWORD: "changeme"
  MQTT_USERNAME: "mqttuser"
  MQTT_PASSWORD: "changeme"

env:
  LEAF_TYPE: ""
  MQTT_HOST: ""
  MQTT_PORT: 1883
  MQTT_BASE_TOPIC: leaf
  UPDATE_INTERVAL_MINUTES: 60
  CHARGING_UPDATE_INTERVAL_MINUTES: 60
  LOG_LEVEL: "Warning"
