image:
  repository: tccr.io/truecharts/nzbhydra2
  pullPolicy: IfNotPresent
  tag: v4.3.3@sha256:5dbf3c2e6ae9b7d26e7edea6e0595e3e597bfaaeefaa26e1e1802ba919f40bc5

securityContext:
  readOnlyRootFilesystem: false

service:
  main:
    ports:
      main:
        port: 5076
        targetPort: 5076

probes:
  liveness:
    custom: true
    enabled: true
    spec:
      failureThreshold: 5
      httpGet:
        path: /actuator/health/livenessState
        port: main
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 10
  readiness:
    custom: true
    enabled: true
    spec:
      failureThreshold: 5
      httpGet:
        path: /actuator/health/readinessState
        port: main
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 10
  startup:
    custom: true
    enabled: true
    spec:
      failureThreshold: 5
      httpGet:
        path: /actuator/health/readinessState
        port: main
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 10

persistence:
  config:
    enabled: true
    mountPath: "/config"
