apiVersion: v2
appVersion: "5.0.9"
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 10.0.14
deprecated: false
description: Fast, reliable, scalable, and easy to use open-source no-sql database system.
home: https://github.com/truecharts/apps/tree/master/charts/dependency/mongodb
icon: https://truecharts.org/_static/img/appicons/mongodb.png
keywords:
  - mongodb
  - database
  - nosql
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: mongodb
sources:
  - https://hub.docker.com/r/bitnami/mongodb
  - https://github.com/bitnami/bitnami-docker-mongodb
  - https://www.mongodb.com
type: application
version: 1.0.13
annotations:
  truecharts.org/catagories: |
    - database
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
