apiVersion: v2
appVersion: "0.8.1"
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 10.0.10
description: An application that lets you automatically process files through a simple rule flow.
home: https://github.com/truecharts/apps/tree/master/charts/stable/fileflows
icon: https://truecharts.org/_static/img/appicons/fileflows.png
keywords:
- fileflows
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: fileflows
sources:
- https://github.com/revenz/FileFlows
- https://hub.docker.com/r/revenz/fileflows
version: 2.0.8
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
