apiVersion: v2
appVersion: "9.39.1"
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 10.0.10
description: CyberChef is a simple, intuitive web app for carrying out all manner of "cyber" operations within a web browser.
home: https://github.com/truecharts/apps/tree/master/charts/stable/cyberchef
icon: https://truecharts.org/_static/img/appicons/cyberchef.png
keywords:
- cyberchef
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: cyberchef
sources:
- https://hub.docker.com/r/mpepping/cyberchef
version: 2.0.11
annotations:
  truecharts.org/catagories: |
    - utilities
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
