image:
  repository: tccr.io/truecharts/cyberchef
  tag: v9.39.1@sha256:c0f61aade1501305e327f8d72c6ee961cee2536b84208651ee0d1729ac332479
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 10219
        targetPort: 8000
