apiVersion: v2
appVersion: "1.6.15"
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 10.0.14
deprecated: false
description: Memcached is a memory-backed database caching solution
home: https://github.com/truecharts/apps/tree/master/charts/dependency/memcached
icon: https://truecharts.org/_static/img/appicons/memcached.png
keywords:
- memcached
- database
- cache
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: memcached
sources:
  - https://github.com/bitnami/bitnami-docker-memcached
  - http://memcached.org/
type: application
version: 3.0.12
annotations:
  truecharts.org/catagories: |
    - database
    - cache
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
