image:
  repository: ghcr.io/truecharts/memcached
  pullPolicy: IfNotPresent
  tag: v1.6.15@sha256:b959d1cb3d5888410c78d3ca31aab88e200bbdac0a6231c82ac6283f7e8881b8

service:
  main:
    ports:
      main:
        port: 11211
        targetPort: 11211
