apiVersion: v2
appVersion: "latest"
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 10.0.10
description: CUPS printing server
home: https://github.com/truecharts/apps/tree/master/charts/incubator/cups-server
icon: https://truecharts.org/_static/img/appicons/cups-server.png
keywords:
- print
- cups
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: cups-server
sources:
- https://hub.docker.com/r/ydkn/cups
version: 1.0.6
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
