apiVersion: v2
appVersion: "2.0.21"
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 10.0.10
description: Audiobookshelf is a self-hosted audiobook server for managing and playing your audiobooks.
home: https://github.com/truecharts/apps/tree/master/charts/stable/audiobookshelf
icon: https://truecharts.org/_static/img/appicons/audiobookshelf.png
keywords:
- audiobookshelf
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: audiobookshelf
sources:
- https://hub.docker.com/r/advplyr/audiobookshelf
- https://github.com/advplyr/audiobookshelf
version: 2.0.6
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
