image:
  repository: tccr.io/truecharts/website-shot
  tag: latest@sha256:fb76cbdf2c81fd93faf0eee4d49db5d3fd18ad6064e7bc1bdbb52a66cb16715e
  pullPolicy: IfNotPresent

service:
  main:
    ports:
      main:
        port: 10221
        targetPort: 3000

persistence:
  screenshots:
    enabled: true
    mountPath: "/usr/src/website-shot/screenshots"
