apiVersion: v2
appVersion: "7.0.2"
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 10.0.14
deprecated: false
description: Open source, advanced key-value store.
home: https://github.com/truecharts/apps/tree/master/charts/dependency/redis
icon: https://truecharts.org/_static/img/appicons/redis.png
keywords:
  - redis
  - keyvalue
  - database
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: redis
sources:
  - https://github.com/bitnami/bitnami-docker-redis
  - http://redis.io/
type: application
version: 3.0.13
annotations:
  truecharts.org/catagories: |
    - database
    - cache
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
