apiVersion: v2
appVersion: "0.57.0"
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 10.0.10
- condition: exporters.enabled,exporters.node-exporter.enabled
  name: node-exporter
  repository: https://charts.bitnami.com/bitnami
  version: 3.0.3
- condition: exporters.enabled,exporters.kube-state-metrics.enabled
  name: kube-state-metrics
  repository: https://charts.bitnami.com/bitnami
  version: 3.1.0
deprecated: false
description: kube-prometheus-stack collects Kubernetes manifests, Grafana dashboards, and Prometheus rules combined with documentation and scripts to provide easy to operate end-to-end Kubernetes cluster monitoring with Prometheus using the Prometheus Operator.
icon: https://truecharts.org/_static/img/appicons/prometheus.png
home: https://github.com/truecharts/apps/tree/master/charts/core/prometheus
keywords:
- metrics
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: prometheus
sources:
  - https://github.com/prometheus-community/helm-charts
  - https://github.com/prometheus-operator/kube-prometheus
type: application
version: 4.0.11
annotations:
  truecharts.org/catagories: |
    - metrics
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
